In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings as wr
wr.filterwarnings('ignore')

In [14]:
df = pd.read_csv("Healthcare-Diabetes.csv")
print(df.head())

   Id  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0   1            6      148             72             35        0  33.6
1   2            1       85             66             29        0  26.6
2   3            8      183             64              0        0  23.3
3   4            1       89             66             23       94  28.1
4   5            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Id,2768.0,1384.500000,799.197097,1.000,692.750,1384.500,2076.250,2768.00
Pregnancies,2768.0,3.742775,3.323801,0.000,1.000,3.000,6.000,17.00
Glucose,2768.0,121.102601,32.036508,0.000,99.000,117.000,141.000,199.00
BloodPressure,2768.0,69.134393,19.231438,0.000,62.000,72.000,80.000,122.00
SkinThickness,2768.0,20.824422,16.059596,0.000,0.000,23.000,32.000,110.00
Insulin,2768.0,80.127890,112.301933,0.000,0.000,37.000,130.000,846.00
BMI,2768.0,32.137392,8.076127,0.000,27.300,32.200,36.625,80.60
DiabetesPedigreeFunction,2768.0,0.471193,0.325669,0.078,0.244,0.375,0.624,2.42
Age,2768.0,33.132225,11.777230,21.000,24.000,29.000,40.000,81.00
Outcome,2768.0,0.343931,0.475104,0.000,0.000,0.000,1.000,1.00

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2768 entries, 0 to 2767
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        2768 non-null   int64
 1   Pregnancies               2768 non-null   int64
 2   Glucose                   2768 non-null   int64
 3   BloodPressure             2768 non-null   int64
 4   SkinThickness             2768 non-null   int64
 5   Insulin                   2768 non-null   int64
 6   BMI                       2768 non-null   float64
 7   DiabetesPedigreeFunction  2768 non-null   float64
 8   Age                       2768 non-null   int64
 9   Outcome                   2768 non-null   int64
dtypes: float64(2), int64(8)
memory usage: 216.4 KB

In [25]:
out1 = df.query('Outcome == 1')
out1.describe().T

,count,mean,std,min,25%,50%,75%,max
Id,952.0,1377.549370,804.884280,1.000,693.500,1405.500,2079.500,2767.00
Pregnancies,952.0,4.769958,3.743430,0.000,1.000,4.000,7.250,17.00
Glucose,952.0,141.481092,31.986618,0.000,119.000,140.000,167.000,199.00
BloodPressure,952.0,71.070378,21.169147,0.000,66.000,74.000,82.000,114.00
SkinThickness,952.0,22.501050,17.623233,0.000,0.000,27.000,36.000,99.00
Insulin,952.0,99.302521,133.111841,0.000,0.000,0.000,167.000,846.00
BMI,952.0,35.270378,7.187776,0.000,30.875,34.300,38.700,67.10
DiabetesPedigreeFunction,952.0,0.543445,0.365979,0.088,0.261,0.439,0.727,2.42
Age,952.0,36.987395,10.930901,21.000,28.000,36.000,44.000,70.00
Outcome,952.0,1.000000,0.000000,1.000,1.000,1.000,1.000,1.00